### ISSUE TITLE
On Windows 11, Clicking start menu button really fast and repeatedly will trigger the shortcut

### ISSUE THREAD

**Issue by the-phuctran** [hereafter/toggle-desktop-icons#1]

**Comment by hereafter** [comment]
bug received, investigating

**Comment by hereafter** [comment]
I have hard time to reproduce it consistently, however I have made changes to the logic to identify desktop more accurately.
I posted an update 1.1.5 to the store. It will be updated soon, please kindly let me know if this helps.

**Comment by the-phuctran** [comment]
thank you it works great.
